# 使用傳統的 node_modules 而非 Plug'n'Play
# 原因：Element Plus 在 PnP 模式下有依賴解析問題
nodeLinker: node-modules

# 為 Element Plus 添加缺失的依賴聲明
packageExtensions:
  element-plus@*:
    dependencies:
      "@vue/shared": "*"
